apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudbanking-backend
  namespace: cloudbanking
  labels:
    app: cloudbanking-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudbanking-backend
  template:
    metadata:
      labels:
        app: cloudbanking-backend
    spec:
      containers:
        - name: backend
          image: 777208093235.dkr.ecr.eu-central-1.amazonaws.com/cloudbanking-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

          env:
            - name: NODE_ENV
              value: "production"

            - name: PORT
              value: "3000"

            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-db-secret
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: backend-db-secret
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-db-secret
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend-db-secret
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-db-secret
                  key: DB_PASSWORD

            - name: DB_SSL
              valueFrom:
                secretKeyRef:
                  name: backend-db-secret
                  key: DB_SSL

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi