apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: cloudbanking
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-db-external-secret
  namespace: cloudbanking
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: backend-db-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: cloudbanking-dev/backend/db
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: cloudbanking-dev/backend/db
        property: DB_PORT
    - secretKey: DB_NAME
      remoteRef:
        key: cloudbanking-dev/backend/db
        property: DB_NAME
    - secretKey: DB_USER
      remoteRef:
        key: cloudbanking-dev/backend/db
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: cloudbanking-dev/backend/db
        property: DB_PASSWORD
    - secretKey: DB_SSL
      remoteRef:
        key: cloudbanking-dev/backend/db
        property: DB_SSL