{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecret.secretStoreName }}
  namespace: {{ .Values.namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecret.region }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.externalSecretName }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecret.targetSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: {{ .Values.externalSecret.awsSecretName }}
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: {{ .Values.externalSecret.awsSecretName }}
        property: DB_PORT
    - secretKey: DB_NAME
      remoteRef:
        key: {{ .Values.externalSecret.awsSecretName }}
        property: DB_NAME
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.externalSecret.awsSecretName }}
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.awsSecretName }}
        property: DB_PASSWORD
    - secretKey: DB_SSL
      remoteRef:
        key: {{ .Values.externalSecret.awsSecretName }}
        property: DB_SSL
{{- end }}