{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.alb.scheme | quote }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.alb.targetType | quote }}
    alb.ingress.kubernetes.io/listen-ports: {{ .Values.ingress.alb.listenPorts | toJson | quote }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.alb.certificateArn | quote }}
    alb.ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.alb.sslRedirect | quote }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}