apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudbanking-backend
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ameeradel/cloudbanking.git
    targetRevision: main
    path: helm/cloudbanking-backend

    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: cloudbanking

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false